-- Tournament and Challenge Tables
USE `zh_love_db`;

-- Tournaments Table
CREATE TABLE `tournaments` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) NOT NULL,
  `name` varchar(200) NOT NULL,
  `description` text DEFAULT NULL,
  `banner_image` varchar(255) DEFAULT NULL,
  `organizer_id` int(11) UNSIGNED NOT NULL,
  `type` enum('single_elimination','double_elimination','round_robin','swiss','ladder') DEFAULT 'single_elimination',
  `game_mode` enum('1v1','2v2','3v3','4v4','ffa','custom') DEFAULT '1v1',
  `prize_pool` decimal(10,2) DEFAULT 0.00,
  `prize_currency` varchar(10) DEFAULT 'USD',
  `entry_fee` decimal(10,2) DEFAULT 0.00,
  `max_participants` int(11) DEFAULT 64,
  `min_participants` int(11) DEFAULT 8,
  `registration_start` timestamp NULL DEFAULT NULL,
  `registration_end` timestamp NULL DEFAULT NULL,
  `tournament_start` timestamp NULL DEFAULT NULL,
  `tournament_end` timestamp NULL DEFAULT NULL,
  `rules` text DEFAULT NULL,
  `map_pool` json DEFAULT NULL,
  `stream_url` varchar(255) DEFAULT NULL,
  `challonge_id` varchar(50) DEFAULT NULL,
  `status` enum('draft','registration','ongoing','completed','cancelled') DEFAULT 'draft',
  `is_featured` tinyint(1) DEFAULT 0,
  `is_public` tinyint(1) DEFAULT 1,
  `participant_count` int(11) DEFAULT 0,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `organizer_id` (`organizer_id`),
  KEY `idx_status` (`status`),
  KEY `idx_is_featured` (`is_featured`),
  KEY `idx_tournament_start` (`tournament_start`),
  KEY `idx_registration_end` (`registration_end`),
  CONSTRAINT `tournaments_organizer_id_foreign` FOREIGN KEY (`organizer_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tournament Participants Table
CREATE TABLE `tournament_participants` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tournament_id` int(11) UNSIGNED NOT NULL,
  `user_id` int(11) UNSIGNED NOT NULL,
  `team_name` varchar(100) DEFAULT NULL,
  `seed` int(11) DEFAULT NULL,
  `status` enum('registered','confirmed','eliminated','winner','runner_up') DEFAULT 'registered',
  `placement` int(11) DEFAULT NULL,
  `prize_won` decimal(10,2) DEFAULT 0.00,
  `registered_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `confirmed_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tournament_user_unique` (`tournament_id`, `user_id`),
  KEY `tournament_id` (`tournament_id`),
  KEY `user_id` (`user_id`),
  KEY `idx_status` (`status`),
  CONSTRAINT `tournament_participants_tournament_id_foreign` FOREIGN KEY (`tournament_id`) REFERENCES `tournaments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tournament_participants_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tournament Matches Table
CREATE TABLE `tournament_matches` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) NOT NULL,
  `tournament_id` int(11) UNSIGNED NOT NULL,
  `round` int(11) NOT NULL,
  `match_number` int(11) NOT NULL,
  `player1_id` int(11) UNSIGNED DEFAULT NULL,
  `player2_id` int(11) UNSIGNED DEFAULT NULL,
  `winner_id` int(11) UNSIGNED DEFAULT NULL,
  `score_player1` int(11) DEFAULT 0,
  `score_player2` int(11) DEFAULT 0,
  `map_name` varchar(100) DEFAULT NULL,
  `replay_file` varchar(255) DEFAULT NULL,
  `stream_url` varchar(255) DEFAULT NULL,
  `status` enum('scheduled','live','completed','forfeit','disputed') DEFAULT 'scheduled',
  `scheduled_at` timestamp NULL DEFAULT NULL,
  `started_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `tournament_id` (`tournament_id`),
  KEY `player1_id` (`player1_id`),
  KEY `player2_id` (`player2_id`),
  KEY `winner_id` (`winner_id`),
  KEY `idx_status` (`status`),
  KEY `idx_round` (`round`),
  CONSTRAINT `tournament_matches_tournament_id_foreign` FOREIGN KEY (`tournament_id`) REFERENCES `tournaments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tournament_matches_player1_id_foreign` FOREIGN KEY (`player1_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `tournament_matches_player2_id_foreign` FOREIGN KEY (`player2_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `tournament_matches_winner_id_foreign` FOREIGN KEY (`winner_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Challenges Table
CREATE TABLE `challenges` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) NOT NULL,
  `challenger_id` int(11) UNSIGNED NOT NULL,
  `challenged_id` int(11) UNSIGNED NOT NULL,
  `title` varchar(200) NOT NULL,
  `description` text DEFAULT NULL,
  `game_mode` enum('1v1','2v2','3v3','4v4','ffa','custom') DEFAULT '1v1',
  `map_name` varchar(100) DEFAULT NULL,
  `wager_amount` decimal(10,2) DEFAULT 0.00,
  `wager_currency` varchar(10) DEFAULT 'USD',
  `rules` text DEFAULT NULL,
  `status` enum('pending','accepted','declined','completed','disputed','cancelled') DEFAULT 'pending',
  `scheduled_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `winner_id` int(11) UNSIGNED DEFAULT NULL,
  `score_challenger` int(11) DEFAULT 0,
  `score_challenged` int(11) DEFAULT 0,
  `replay_file` varchar(255) DEFAULT NULL,
  `stream_url` varchar(255) DEFAULT NULL,
  `admin_approved` tinyint(1) DEFAULT 0,
  `approved_by` int(11) UNSIGNED DEFAULT NULL,
  `approved_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `challenger_id` (`challenger_id`),
  KEY `challenged_id` (`challenged_id`),
  KEY `winner_id` (`winner_id`),
  KEY `approved_by` (`approved_by`),
  KEY `idx_status` (`status`),
  KEY `idx_scheduled_at` (`scheduled_at`),
  CONSTRAINT `challenges_challenger_id_foreign` FOREIGN KEY (`challenger_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `challenges_challenged_id_foreign` FOREIGN KEY (`challenged_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `challenges_winner_id_foreign` FOREIGN KEY (`winner_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `challenges_approved_by_foreign` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 